# Generated by Django 4.1.2 on 2022-10-27 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_department_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_spec', models.CharField(max_length=255)),
                ('doctor_image', models.ImageField(upload_to='doctors')),
                ('doctor_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.department')),
            ],
        ),
    ]
